### ISSUE TITLE
Please share required module (Autoload v4)

### ISSUE THREAD

**Issue by bielawb** [Jaykul/Reflection#1]
It would be great if you could share also module that you marked as required in module manifest. ;)

I had no luck finding [Autoload 4.0](https://github.com/Jaykul/Reflection/blob/master/Reflection.psd1#L43). And yes, I know there is [Chocoloatey package](http://chocolatey.org/packages/autoload) with newer version, but I would love to stay away from this packaging tool (at least for now).

**Comment by Jaykul** [comment]
I finally did this here on GitHub https://github.com/Jaykul/Autoload
And re-published this to the PowerShellGallery with dependencies working.
